### ISSUE TITLE
iOS 9 Backups don't show up

### ISSUE THREAD

**Issue by kkirby** [horrorho/LiquidDonkey#2]
As the title says, iOS 9 backups don't appear. I'm not sure if this is simply because the application is omitting them (or Apple is omitting them), or they've changed something on a larger scale.

**Comment by horrorho** [comment]
Hi. It wouldn't surprise me if something changed on Apple's end. I don't have an iOS 9 device at the moment to test with, so my options are limited.

I would suggest:

- Double check the backups are showing up in the iCloud Storage area: [Manage your iCloud storage](https://support.apple.com/en-gb/HT204247).
- Try [iLoot](https://github.com/hackappcom/iloot). LiquidDonkey uses the same API calls.
- If iLoot works, then there's a bug in LiquidDonkey.
- If iLoot also doesn't work, I'd suggest opening a ticket there along with any error messages you may receive.

Either way, if you would kindly let me know. If iLoot also doesn't work, then it will be wait until either iLoot is updated so I can port over the changes, or the new protocol details are published elsewhere.

**Comment by kkirby** [comment]
The issue exists in iLoot also.

**Comment by horrorho** [comment]
Thank you for getting to back to me so quickly. I'm afraid it's going to be a wait until someone figures out a workaround and publishes it. I'll keep my eyes open and update as soon as I have something to work with.

I will endeavour to acquire an iOS 9 device in the meantime to see if there is a trivial fix that can be applied.

Sorry I can't be much more help at the moment.

**Comment by ciucaandrei** [comment]
I left a comment on the iLoot page. I did not get an answer yet.
The backup structure seems the same. I think that the encryption is also the same. But somehow it is like it's connecting to a different server.

**Comment by horrorho** [comment]
Thank you for the feedback. I've subscribed to your ticket and I'll keep an eye on any developments. I'm still waiting for an iOS 9 device so I can look into it.

**Comment by horrorho** [comment]
It looks like the underlying API has changed. Rumours suggest CloudKit for which I have no details.

Until the new iCloud API has been described, I'm unable to update LiquidDonkey. Apologies in advance.

I'll leave this ticket open and update if I have any meaningful news.

I'll also monitor the  [iLoot](https://github.com/hackappcom/iloot) situation. Although you are welcome to comment here, to avoid fragmenting discussion it might be better to leave iOS 9  feedback [there](https://github.com/hackappcom/iloot/issues/62).

**Comment by mdPlusPlus** [comment]
It's been some months now, any news?

**Comment by horrorho** [comment]
Hi there. I've been struggling for free time but that being said, I have been working on the issue over the last week. I have some avenues to explore and I'll report any findings over [here](https://github.com/hackappcom/iloot/issues/62).

**Comment by prateek1108** [comment]
Hi,
I am also facing the same issue on ios 9 icloud backup backups of ios 8 and below are listed. i also tried iloot same issue is there in that.

**Comment by horrorho** [comment]
Oops. Forgot to close this issue.

Use [InflatableDonkey](https://github.com/horrorho/InflatableDonkey) for iOS9+ backups.
