### ISSUE TITLE
Compilation error on Windows 7

### ISSUE THREAD

**Issue by lucba** [horrorho/LiquidDonkey#3]
Hi,

I get this compilation error on Windows 7 with JDK 8u60 and Maven 3.3.3. Any idea what's wrong?

    [INFO] -------------------------------------------------------------
    [ERROR] COMPILATION ERROR :
    [INFO] -------------------------------------------------------------
    [ERROR] /C:/PortablePrograms/LiquidDonkey-master/src/main/java/com/github/horror
    ho/liquiddonkey/settings/config/FileFilterConfig.java:[66,42] reference to paths
     is ambiguous
      both method paths(java.lang.String) in com.github.horrorho.liquiddonkey.settin
    gs.config.ItemTypes and method paths(java.util.List<java.lang.String>) in com.gi
    thub.horrorho.liquiddonkey.settings.config.ItemTypes match
    [ERROR] /C:/PortablePrograms/LiquidDonkey-master/src/main/java/com/github/horror
    ho/liquiddonkey/settings/config/FileFilterConfig.java:[66,66] incompatible types
    : cannot infer type-variable(s) T
        (actual and formal argument lists differ in length)
    [INFO] 2 errors
    [INFO] -------------------------------------------------------------
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 01:17 min
    [INFO] Finished at: 2015-09-23T14:51:45+01:00
    [INFO] Final Memory: 20M/246M
    [INFO] ------------------------------------------------------------------------
    [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.
    1:compile (default-compile) on project LiquidDonkey: Compilation failure: Compil
    ation failure:
    [ERROR] /C:/PortablePrograms/LiquidDonkey-master/src/main/java/com/github/horror
    ho/liquiddonkey/settings/config/FileFilterConfig.java:[66,42] reference to paths
     is ambiguous
    [ERROR] both method paths(java.lang.String) in com.github.horrorho.liquiddonkey.
    settings.config.ItemTypes and method paths(java.util.List<java.lang.String>) in
    com.github.horrorho.liquiddonkey.settings.config.ItemTypes match
    [ERROR] /C:/PortablePrograms/LiquidDonkey-master/src/main/java/com/github/horror
    ho/liquiddonkey/settings/config/FileFilterConfig.java:[66,66] incompatible types
    : cannot infer type-variable(s) T
    [ERROR] (actual and formal argument lists differ in length)

**Comment by horrorho** [comment]
Thank for the report! I've managed to replicate the error and have pushed a new build which compiles on Oracle JDK 8u60.

Please let me know if the issue still persists on your end with the new build.

**Comment by horrorho** [comment]
Closing.
