### ISSUE TITLE
Illegal Characters & Weird Print Issues

### ISSUE THREAD

**Issue by jkmalan** [horrorho/LiquidDonkey#4]
Hi, while running the most recent version of LiquidDonkey, I received errors related to illegal characters. I am on Windows, so I assume characters such as * and : caused LiquidDonkey to error while writing.

I wanted to post a stack trace, but am having difficulty because when running LiquidDonkey from command prompt, powershell, or cygwin, for some reason no text appears, or I get only a few random characters that look like parts of a word. I hit enter around the time at that first : to select all backups for download and then it runs a little and errors.

[Cygwin Terminal Screenshot](https://cloud.githubusercontent.com/assets/1034481/10867598/b5d39ffa-8038-11e5-98b7-ad10bb9ec20d.png)
[Powershell Screenshot](https://cloud.githubusercontent.com/assets/1034481/10867599/b5d5ee9a-8038-11e5-9bdb-583252dea47d.png)
[Command Screenshot](https://cloud.githubusercontent.com/assets/1034481/10867597/b5d280a2-8038-11e5-8e3c-762072a44fdb.png)

**Comment by horrorho** [comment]
Hi! Thank you for the report. I'll try and replicate the fault and see if I can figure out what the issue is. I am otherwise engaged for the rest of today, so unfortunately it won't be until tomorrow at the earliest. Sorry.

**Comment by horrorho** [comment]
Ok! I've managed to take a few minutes to have a look at it. I've identified and replaced the troublesome code for the blank lines on Windows based consoles. Thank you for the screen shots which helped clarify the issue.

As for the illegal characters,  I couldn't replicate the issue with VM Windows 7 command prompt:
```
java -jar LiquidDonkey.jar -o E:\Assorted\iCloud id@apple.com password
```
```
C:\temp>java -version
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) Client VM (build 25.60-b23, mixed mode, sharing)
```
Maybe try wrapping the output path in quotes:
```
java -jar LiquidDonkey.jar -o "E:\Assorted\iCloud" id@apple.com password
```
Either way, the stack trace should now function which should provide us with clues. If you could kindly try out the new build and report back.

**Comment by jkmalan** [comment]
After running the recompiled build, it was nice to see some text :)

Here's the full stack trace:
[Command Screenshot](https://cloud.githubusercontent.com/assets/1034481/10870161/daec2c54-8091-11e5-8d50-4dc04d8394c6.png)

**Comment by horrorho** [comment]
Ok! I've pushed a new build. It's an issue with incomplete file name sanitization for Windows. As you stated earlier certain characters do fail in a Windows environment.

Please let me know if the issue persists.

**Comment by jkmalan** [comment]
Issue seems to be totally fixed, thank you very much!
